### ISSUE TITLE
Dynamic Proxy integration 4.3.0 doesn't work with Castle.Core 4.2.1

### ISSUE THREAD

**Issue by monksoul** [autofac/Autofac.Extras.DynamicProxy#25]

**Comment by tillig** [comment]
Can you provide a bit more info here? Is there an error message? Some reproduction you can show to illustrate the problem?

**Comment by hikalkan** [comment]
I'm getting this exception for `registrationBuilder.EnableClassInterceptors()` method.

````
Message: System.IO.FileNotFoundException : Could not load file or assembly 'Castle.Core, Version=4.1.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'. The system cannot find the file specified.
````

![image](https://user-images.githubusercontent.com/1210527/36073955-df1d25b4-0f49-11e8-92fe-f1902b6bd803.png)

I'm using Castle.Core v4.2.1 as shown in the image above.

**Comment by tillig** [comment]
You may need to add an assembly binding redirect to your app.config. NuGet sometimes misses that.
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by hikalkan** [comment]
I've already `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` in my csproj file.

**Comment by hikalkan** [comment]
Even adding this didn't help:

````xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
````

Getting the exception on runtime, it's not a build problem. So, it may not be related to nuget.

**Comment by tillig** [comment]
Binding redirects are a runtime thing (note the `runtime` element).

Is there a small repro project I can see?

**Comment by tillig** [comment]
Also, have you tried clearing cached items like the .vs folder? That can sometimes help.

**Comment by hikalkan** [comment]
Yes, I cleared it. I also published it and run under IIS to see the difference. Result is same.

> Is there a small repro project I can see?

No, but nice idea, I can try with a simpler test project when I have time.

**Comment by tillig** [comment]
I was able to repro this in a small console app. Unclear why it's popping up yet or what to do about it, but at least I see it.

**Comment by tillig** [comment]
OK, it turns out this is a Castle.Core problem. TL;DR: They wanted to switch from changing their assembly version strategy so it's pinned at 4.0.0.0... but they did that after having released 4.1.0.0. As of Castle.Core 4.2.0, the Castle.Core _package version_ changes but the _assembly version_ doesn't. And they chose to go _backwards_ to 4.0.0. assembly version instead of stopping at 4.1.0.0 and pinning there... or restarting at 5.0.0.0.

- https://github.com/castleproject/Core/issues/288
- https://github.com/castleproject/Core/issues/307

What a nightmare.

I guess the right way to handle this is to update to 4.2.1 here so the bound assembly version lines up...? This is going to be a nightmare of trickle down problems. Sigh. But I can't see any way around it. Really wish they hadn't done that without incrementing the major version.

**Comment by hikalkan** [comment]
OMG! Then upgrading dependency to 4.2.1 seems the best way.

**Comment by tillig** [comment]
I released v4.4.0 of Autofac.Extras.DynamicProxy that uses Castle.Core 4.2.1. I also [added docs about this issue](http://autofac.readthedocs.io/en/latest/advanced/interceptors.html). That's the best I can do from this end.

For folks hitting this in the future, I recommend taking it up with the Castle.Core crew. This is out of the control of Autofac.

**Comment by hikalkan** [comment]
Thank you @tillig for fast reaction. I just tested and it worked :)

**Comment by alexmg** [comment]
Nice work @tillig. I've updated `Autofac.ServiceFabric` to this new release. 👍
